# Generated by Django 5.1.1 on 2024-09-15 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('apple', 'Alma'), ('plum', 'Szilva'), ('apricot', 'Barack'), ('sour_cherry', 'Cigány meggy'), ('grape', 'Szőlő')], max_length=50)),
                ('harvest_date', models.DateField()),
                ('weight_kg', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='Fermentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('final_yield_l', models.FloatField(blank=True, null=True)),
                ('alcohol_percentage', models.FloatField(blank=True, null=True)),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fruit')),
            ],
        ),
        migrations.CreateModel(
            name='PHMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ph_value', models.FloatField()),
                ('fermentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fermentation')),
            ],
        ),
        migrations.CreateModel(
            name='SugarMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sugar_content_percent', models.FloatField()),
                ('fermentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fermentation')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature_c', models.FloatField()),
                ('fermentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fermentation')),
            ],
        ),
    ]
